<img align="left" width="300" src="https://drive.google.com/uc?id=1xhBJo9KKicDMw6HuOCZiRclX5DJb2g_J">

# **Linear Algebra in Python**
# TReND Course in Computational neuroscience and machine learning basics




---
## **Learning objectives**:
* Getting a sense of some of the basic linear algebra concepts like vectors, matrices and their simple properties and operations 
* Using the Python package NumPy, being able to implement the basic linear algebra operations

## **Content:**
1. [Why learn linear algebra?](#why)
2. [Vectors in Python](#vectors)
3. [Matrices in Python](#matrices)
4. [Resources](#resources)


---
#**Section 1.** Why learn linear algebra? <a name="why"></a>

Linear algebra is a powerful tool that is **used in many fields**:
- Maths, physics
- **Machine learning**
- **Neurosciences**
- Biology 
- Medicine
- Chemistry
- Economics
- Engineering
- ...


Linear algebra **enables us to work with data**.
- Data analysis (representation, operations, ...) including high dimensional data
- Solving systems of linear equations
- Optimization



---
# **Section 2. Vectors in Python** <a name="vectors"></a>
Vector is one of the most fundamental object of linear algebra.



A very general definition: 
**Vectors are ordered lists of numbers.** But how does this relate with data?

Example: We measured the heights of 3 people (in centimeters), and recorded the following numbers: 158, 175, 190. We can represent this data in a vector:

$\mathbf{heights} = \begin{bmatrix} 158 \\ 175 \\ 190 \end{bmatrix}$

**Vectors can also be viewed from a geometric perspective:**

- Arrows starting from the origin at a coordinate system.
- The ordered set of numbers define where the arrow is pointing at.


Let's visualize a vector of our choice geometrically:

$\mathbf{vector} = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}$

Change $x_1$ and $x_2$ and see how the arrow changes:

In [ ]:
#@title Run this for visualizing our vector.
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets  # interactive display
from ipywidgets import fixed
%config InlineBackend.figure_format = 'retina'

def plot_arrow(x):
  fig, ax = plt.subplots(figsize=(5, 5))

  origin = np.array([0, 0]) # origin point

  plt.quiver(*origin, x[0], x[1], color='k',scale=20)
  plt.xlim([-10,10])
  plt.ylim([-10,10])
  plt.xlabel('$x_1$')
  plt.ylabel('$x_2$')


  plt.show()

@widgets.interact(x1 = widgets.FloatSlider(value=1.0, min=-10, max=10, step=0.5), x2 = widgets.FloatSlider(value=1.0, min=-10, max=10, step=0.5))
def plot_linear_combination(x1, x2):
  x = np.array([x1, x2])
  plot_arrow(x)



interactive(children=(FloatSlider(value=1.0, description='x1', max=10.0, min=-10.0, step=0.5), FloatSlider(val…

### 2.1 Our first vector

To work with vectors in Python, we'll use the package **NumPy**.

Before using NumPy in our code, we need to import it:

In [ ]:
# Import the required package


In [ ]:
#@title Double click here for the solution
import numpy as np

Now that we imported numpy let's create the following vector:

$\mathbf{x} = \begin{bmatrix} 3 \\ 5 \\ 2 \end{bmatrix}$

- In NumPy vectors are represented as **arrays**:

```x = np.array([3,5,2])```



create the following vector using NumPy:

$\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 2 \\ 4 \end{bmatrix}$

In [ ]:
# Your answer goes here

In [ ]:
#@title Double click here for the solution
x = np.array([1,2,2,4])

You just created your first vector using NumPy, congrats!

### 2.2 Simple properties of a vector

As data have different properties, we can check our vector's properties to get a sense of our data. 

#### Dimensionality

The dimensions of a vector reflects **the number of elements in the vector**. 

What does this mean in terms of our data?? Let's figure it out:

We have two datasets:
- ```heights```: we measured the heights of people walking on the street and put it inside a vector. 
- ```spikes```: we measured the activities of different neurons (spikes) in the brain of a mouse and put it inside a vector.

but we forgot how many people and neurons we measured...

In [ ]:
#@title run this first to generate data
heights = np.random.randint(120,200,150)
spikes = np.random.randint(0,50,2000)

We can check the dimension of our vector $\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 2 \\ 4 \end{bmatrix}$ in the following way:

```x.shape```

In [ ]:
x = np.array([1,2,2,4])
x.shape

(4,)

**Your turn:** Find out how many people and neurons were measured. Our data is in the vectors named ```heights``` and ```spikes```.

In [ ]:
# Your answer goes here

In [ ]:
#@title Double click here for the solution
n_people = heights.shape
n_neurons = spikes.shape

#### Length (norm) of a vector

Measuring the length of a vector is important to know in linear algebra. Length is also called the **norm** of a vector. 

There are several ways of computing the length of a vector, the **Euclidiean norm** (a.k.a. $L_2$ norm) is a common way in machine learning or comp. neuro. applications:

\begin{equation}
||\mathbf{x}|| = \sqrt{\sum_{i=1}^N \mathbf{x}_i^2}
\end{equation}




In Python, we can compute the norm using:

```np.linalg.norm()```

Compute the L2 norm of $\mathbf{x} = \begin{bmatrix}  2 \\ 4 \end{bmatrix}$

In [ ]:
# Your answer goes here

In [ ]:
#@title Double click here for the solution
x=np.array([2,4])
np.linalg.norm(x)

**Tip:** you can calculate different norms of the vectors by providing a different second argument to the ```np.linalg.norm()``` function:

- **Euclediean** $L_2$ norm: ```np.linalg.norm(x,2)```
- **Manhattan** $L_1$ norm: ```np.linalg.norm(x,1)```
- **Infinity** norm: ```np.linalg.norm(x, np.inf)```

as you may have noticed in the exercise above, the default behavior of ```np.linalg.norm()``` (default: if we don't give any second argument) is the Euclediean $L_2$ norm.

### 2.3 Simple operations with vectors

We can do many operations using vectors, that's one of the powerful aspects of using linear algebra. Some simple ones include:
- Vector-vector addition
- Vector-scalar multiplication
- Vector-vector multiplication (dot product)


#### Vector-vector addition

Like we do it with numbers, we can also add vectors to other vectors. Here we are adding the pairs of elements of each vector and creating a new vector with the sum in the corresponding location. So if we add vector $\mathbf{x}$ to vector $\mathbf{y}$:

 $$\mathbf{x} + \mathbf{y} = \begin{bmatrix}
           \mathbf{x}_{1} + \mathbf{y}_1 \\ \mathbf{x}_{2} + \mathbf{y}_2\\ \vdots \\ \mathbf{x}_{N} + \mathbf{y}_N 
\end{bmatrix}$$

Let's do this in python. We simply use ```+``` to add vectors.

Add the following vector $\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 2 \\ 4 \end{bmatrix}$ to this $\mathbf{y} = \begin{bmatrix} 5 \\ 2 \\ 3 \\ 1 \end{bmatrix}$ and assign the result to a new vector $\mathbf{z}$.

In [ ]:
# Your answer goes here

In [ ]:
#@title Double click here for the solution
x = np.array([1,2,2,4])
y = np.array([5,2,3,1])
z = x + y
print(z)

#### Vector-scalar multiplication
Multiplying a vector with a scalar leads to each of the vector's elements being multiplied individually with the scalar.

So if we multiply the vector $\mathbf{x}$ with the scalar $a$:
$$ a\mathbf{x} = \begin{bmatrix}
    a\mathbf{x}_1 \\ a\mathbf{x}_2 \\ \vdots \\ a\mathbf{x}_N
\end{bmatrix}$$

Let's do this in python. We simply use ```*``` to multiply a scalar with a vector.

Multiply the following vector $\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 2 \\ 4 \end{bmatrix}$ with the scalar $5$ and assign it to a new vector named $\mathbf{y}$.

In [ ]:
# Your answer goes here

In [ ]:
#@title Double click here for the solution
x = np.array([1,2,2,4])
y = x*5
print(y)

#### Linear combination of vectors

When we apply scalar multiplication and vector addition to several vectors, we get a **linear combination**.

$$\mathbf{u} = c_1\mathbf{v}^1 + c_2\mathbf{v}^2 + ... + c_n\mathbf{v}^N $$.

Linear combinations are fundamental in linear algebra and used in every aspect of linear algebra.

#### Vector-vector multiplication: the dot product

Dot product is a way of multiplying vectors which consists of computing the element-wise multiplication and summing the results. We ultimately get a scalar value.

Let's do the dot product of $\mathbf{x} = \begin{bmatrix}5\\ 1\\\end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix}3\\ 2\\\end{bmatrix}$, then:

\begin{equation}
\mathbf{x} \cdot \mathbf{y} = 5*3 + 1*2 = 16\text{.}
\end{equation}



In Python we use the following notation to compute the dot product:
- ```np.dot(x,y)``` 
- or alternatively and shortly: ```x@y```

Let's use dot product to compute my groceries bill:

I stored the costs of each item here:
```item_costs```

and stored the number of products I bought from each item:
```n_items```


In [ ]:
#@title run this first to generate data
item_costs = np.array([100,65,44.5,32,85,67])
n_items = np.array([1,5,2,3,8,6])

In [ ]:
#Your answer here

In [ ]:
#@title Double click here for the solution

# using np.dot
print(np.dot(item_costs,n_items))
# using @
print(item_costs@n_items)

---
# Section 3. Matrices in Python <a name="matrices"></a>

In vectors we represented a single variable with many instances (heights of people, cost of items, spikes of neurons etc.). 

With matrices, we can represent many instances of multiple variables.

This means **matrices are ordered collection of vectors**:

$\mathbf{v_1} = \begin{bmatrix} 158 \\ 175 \\ 190 \end{bmatrix}$: vector representing heights of 3 people.

$\mathbf{v_2} = \begin{bmatrix} 30 \\ 22 \\ 48 \end{bmatrix}$: vector representing age of these 3 people.

We can represent our data by putting these vectors together in a matrix:

\begin{equation}M = 
\begin{bmatrix}
158 & 30 \\
175 & 22 \\
190 & 48
\end{bmatrix}
\end{equation}


$M$ is a **3x2 matrix**. A generalized way of writing is $m$ x $n$ where $m$ is the number of columns and $n$ is the number of rows.

## Matrix representation

Please create the above matrix in Python:

In [ ]:
#Your code goes here

In [ ]:
#@title Double-click here for the solution
M = np.array([[158, 30],  # 1st row
              [175, 22],
              [190, 48]]) # 2nd row
print(M)

What are the dimensions of M:

In [ ]:
#Your code goes here

In [ ]:
#@title Double-click here for the solution
print(M.shape)

## Simple matrix operations

### Matrix-matrix addition
Similar to the vector-vector addition, we can add two matrices in an element-wise fashion in two ways. Given two matrices $A$ and $B$:
- using ```A + B``` 
- using ```np.add(A,B)``` 

Let's see an example:

\begin{equation}A = 
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix} B = 
\begin{bmatrix}
2 & 1 \\
-5 & 0 
\end{bmatrix}
\end{equation}


\begin{equation}
A+B=
\begin{bmatrix}
1+2 & 2+1 \\
3+(-5) & 0+4 
\end{bmatrix}
=
\begin{bmatrix}
3 & 3 \\
-2 & 4 
\end{bmatrix}
\end{equation}

In [ ]:
# Define the matrices
A = np.array([[1,2],
              [3,4]])
B = np.array([[2,1],
              [-5,0]])

In [ ]:
A+B

array([[ 3,  3],
       [-2,  4]])

In [ ]:
np.add(A,B)

array([[ 3,  3],
       [-2,  4]])

### Matrix-scalar multiplication

Same as vector-scalar multiplication, we can do an element-wise multiplication. We can multiply the above matrix $A$ with a scalar $k$:

\begin{equation}kA = 
\begin{bmatrix}
1 x k & 2 x k \\
3 x k & 4 x k 
\end{bmatrix}
\end{equation}

This can be done in Python:
- using ```k * A``` 
- using ```np.multiply(k,A)``` 


Let's say $k=2$:

In [ ]:
k = 2
k * A

array([[2, 4],
       [6, 8]])

In [ ]:
k = 2
np.multiply(k,A)

array([[2, 4],
       [6, 8]])

## Matrix multiplication

### Matrix-vector multiplication
We can multiply matrix with a vector or matrix with another matrix again using the dot product operator in Python. If we have a matrix $A$ and a vector $x$:

\begin{equation}A = 
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix} x = 
\begin{bmatrix}
2 \\ 1 \\
\end{bmatrix}
\end{equation}



\begin{equation}
A  \cdot x= 2 \begin{bmatrix} 1 \\ 3 \end{bmatrix} + 1 \begin{bmatrix} 2 \\ 4  \end{bmatrix} = \begin{bmatrix} 4 \\ 10 \end{bmatrix}
\end{equation}


- ```np.dot(A,X)``` 
- or alternatively and shortly: ```A@X```

In [ ]:
# Define the matrices
A = np.array([[1,2],
              [3,4]])
x = np.array([2,1])


In [ ]:
np.dot(A,x)

array([ 4, 10])

In [ ]:
A@x

array([ 4, 10])

### Matrix-matrix multiplication: dot product

We can also use the dot product to multiply two matrices. Given matrices $A$ and $B$ to perform a dot product we need:
- \# of columns in A must be equal to # of rows in B.

In [ ]:
# Define the matrices
A = np.array([[1,2],
              [3,4]])
B = np.array([[2,1],
              [-5,0]])

In [ ]:
np.dot(A,B)

array([[ -8,   1],
       [-14,   3]])

In [ ]:
A@B

array([[ -8,   1],
       [-14,   3]])

**Be careful:** Dot product is not an element-wise multiplication of the matrices! To do an element-wise multiplication of $A$ and $B$ (a.k.a. the Hadamard product denoted by $A⊙B$) we use ```np.multiply(A,B)``` or ```A*B```.

## Other important matrix properties

### Transpose of a matrix

Transposing a matrix is a common operation in linear algebra. It is switching the columns by the rows.

\begin{equation}A = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix} A^T = 
\begin{bmatrix}
1 & 3 & 5\\
2 & 4 & 6 
\end{bmatrix}
\end{equation}

In python we transpose a matrix $A$ by:
- ```A.T```
- ```np.transpose(A)```

### Diagonal matrices

A square matrix is called ***diagonal*** when all non-diagonal elements are equal to zero.

\begin{equation}A = 
\begin{bmatrix}
4 & 0 & 0\\
0 & 3 & 0\\
0 & 0 & 1
\end{bmatrix}
\end{equation}

In Python we can get the diagonal elements of a diagonal matrix using ```np.diag(A)```

In [ ]:
A = np.array([[4,0,0],
              [0,3,0],
              [0,0,1]])
print(np.diag(A))

[4 3 1]


### Identity matrix

A diagonal matrix is called ***identity matrix*** when all diagonal elements are equal to $1$.

In Python we can easily build identity matrices of desired shape using:
- ```np.eye(n)``` where $n$ is the number of rows/columns

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse of a matrix

In some operations, we'll be needing to find the inverse of a given matrix. For example:

$A = BC$

we know the matrices $A$ and $B$ and want to solve for $C$. 

we can invert $B$ to $B^{-1}$ and compute the dot product: $A \cdot B^{-1}$.



We invert the matrix $B$ in Python using:

- ```B_i = np.linalg.inv(B)```
- ```B.I```

In [ ]:
B = np.array([[1,2],
              [3,4]])

print(f'B: \n{B}')
print(f'B inverted:\n{np.linalg.inv(B)}')

B: 
[[1 2]
 [3 4]]
B inverted:
[[-2.   1. ]
 [ 1.5 -0.5]]


**Be careful**: Not all matrices are invertible! We say *singular* to the matrices that are noninvertible.

Let's try this:
\begin{bmatrix}
3 & 1 \\
6 & 2  
\end{bmatrix}

In [ ]:
B = np.array([[3, 1], [6, 2]])
print(B)
print(np.linalg.inv(B) )

[[3 1]
 [6 2]]


LinAlgError: ignored

As you saw, we get an error trying to invert a singular matrix.

### Determinant

Determinant is a very important property of a matrix. Determinant is a single value and you can learn a lot by it. 

Determinant can tell you if a matrix is singular or not. If 
- $det(A=0)$, $A$ is singular (noninvertible)

In python we use ```np.linalg.det(A)```

In [ ]:
print(f'determinant of A: {np.linalg.det(B)}')


determinant of A: 0.0


In [ ]:
B = np.array([[3, 1], [6, 2]])
print(B)
print(np.linalg.inv(B) )



[[3 1]
 [6 2]]


LinAlgError: ignored

---
# Section 4. Resources <a name="resources"></a>

## Cheat sheet

A nice cheat sheet for the course from Data Camp:

[Data Camp SciPy Cheat Sheet](https://res.cloudinary.com/dyd911kmh/image/upload/v1676303474/Marketing/Blog/SciPy_Cheat_Sheet.pdf)

## Getting help

NumPy linear algebra documentation:
https://numpy.org/doc/stable/reference/routines.linalg.html

---
# Congrats! That's it for this tutorial. 

**Content Creator:** **Burak Gür**

Some parts inspired/modified from the amazing tutorials of:
- Neuromatch Academy tutorials [W0D3 Linear Algebra](https://compneuro.neuromatch.io/tutorials/W0D3_LinearAlgebra/student/W0D3_Tutorial1.html) by **Ella Batty**
- [Introduction to linear algebra for applied machine learning with Python](https://pabloinsente.github.io/intro-linear-algebra#diagonal-matrix) by **Pablo Caceres**

---
# About the author (feel free to contact)

## Burak Gür
- Post-doctoral researcher in the [lab of Marion Silies](https://ncl-idn.biologie.uni-mainz.de/), JGU Mainz / Germany on visual neuroscience.
- Organizer at the computational neuroscience and deep learning school [Neuromatch Academy](https://academy.neuromatch.io/about/mission).
- Links:
[twitter](https://twitter.com/burakgur_), [Google Scholar](https://scholar.google.com/citations?user=8B2egmgAAAAJ&hl=en), [linkedin](https://www.linkedin.com/in/burak-gur-605701a2/?originalSubdomain=de)
- Feel free to contact me: bguer@uni-mainz.de